name: CI/CD Pipeline for Routine Backend

on:
  push:
    branches:
      - master  # Only trigger when `master` branch is updated

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    environment: production  # Use production environment secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # From environment: production
          password: ${{ secrets.DOCKER_PASSWORD }}  # From environment: production

      - name: Create sentry-auth-token file
        run: echo "${{ secrets.SENTRY_AUTH_TOKEN }}" > .sentry-auth-token  # From repository secrets

      - name: Build & Push Docker Image (Linux only)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64  # Only build for Linux
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/routine-backend:latest
          secrets: |
            id=sentry_token,src=.sentry-auth-token

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    environment: production
    needs: build-and-push

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}  # From repository secrets
