name: CI/CD Pipeline for Routine Backend

on:
  push:
    branches:
      - master  # Only trigger when `master` branch is updated

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image Securely
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/routine-backend:latest
          secrets: |
            id=sentry_token,src=/dev/shm/sentry_token

      - name: Deploy to Render
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

  prepare-secret:
    name: Prepare Secret for Build
    runs-on: ubuntu-latest
    environment: production
    outputs:
      sentry_secret_path: /dev/shm/sentry_token
    steps:
      - name: Create secret file
        run: |
          echo "${{ secrets.SENTRY_AUTH_TOKEN }}" > /dev/shm/sentry_token
